POST http://localhost:3000/auth/oauth
Content-Type: application/json

{
    "name":"dyaz.amrullah@gmail.com",
    "password":"password123"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InNhYnJpbmEiLCJlbWFpbCI6InNhYnJpbmFAbWFpbC5jb20iLCJpYXQiOjE2ODI2OTI2MDh9.VneW1WUp6Cupqe2H4zdYwwc18Ows-8OXnjd1nd1vTCY